### ISSUE TITLE
easy way to match if rendered component includes another one

### ISSUE THREAD

**Issue by iamstarkov** [MoOx/jsx-test-helpers#1]
lets say i have complex component and want to verify that it renders one important child component. `String.prototype.includes` is supposed to work just fine here, but as far as child is nested in parent component it got rendered in parent with extra indentation over child's render.

``` js
test('\0/', t => {
  const Parent = ({ text }) => (<div><a href="/">{ text }</a></div>)
  const actual = renderJSX(<Parent text="some" />);
  const child = JSX(<a href="/">some</a>);

  console.log({
    // see how `\n    some` in parent vs `\n  ` in child
    actual, // '<div>\n  <a href="/">\n    some\n  </a>\n</div>'
    child,  // '<a href="/">\n  some\n</a>'
    result: actual.includes(child) // false
  });
  t.is(actual.includes(child), true); // fail
});
```

**Comment by iamstarkov** [comment]
I would say if both components would be rendered minified-ish, that can solve a problem, but that will complicate debugging. Though, i didnt manage to find `minify` option to render components

**Comment by MoOx** [comment]
Hey. This module is probably too stupid to handle that. 
As you can see, the code si REALLY light https://github.com/MoOx/jsx-test-helpers/blob/master/src/index.js because it's based on `react-element-to-jsx-string` which create the \n.

I would suggest you to use a more complex tool like enzyme for this kind of tests.

**Comment by iamstarkov** [comment]
thanks,

yeah, switched to `enzyme`. though i enjoyed simplicity of this setup
